### ISSUE TITLE
Removed unused import statements

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#11]
<img width="994" alt="Screen Shot 2022-08-12 at 7 55 15 PM" src="https://user-images.githubusercontent.com/7910468/184348966-c5b3ce7a-ee37-45b2-a517-a1cdc00978c7.png">

**Comment by lawgimenez** [comment]
Removed all unused import statements and remove newline.

**Comment by ResurreccionErick** [comment]
Fixed, Thank you sir!
