### ISSUE TITLE
Don't ignore warnings and helpers

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#12]
<img width="752" alt="Screen Shot 2022-08-12 at 7 56 22 PM" src="https://user-images.githubusercontent.com/7910468/184349146-b3572d38-33fb-4d13-aa57-e0c955b451a2.png">

Not ideal to ignore warnings and recommendations. Do what the AS says in the warning.

**Comment by ResurreccionErick** [comment]
Fixed, Thank you sir!
