### ISSUE TITLE
ViewBinding not implemented but declared true in Gradle

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#13]
<img width="227" alt="Screen Shot 2022-08-12 at 7 59 12 PM" src="https://user-images.githubusercontent.com/7910468/184349547-57323d38-f538-47f6-8fca-f03c76d873c0.png">

**Comment by lawgimenez** [comment]
And remove semicolon

**Comment by ResurreccionErick** [comment]
Already deleted, thank you sir!
