### ISSUE TITLE
Avoid using getApplicationContext()

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#19]
For example
```
startActivity(new Intent(getApplicationContext(), ResetUserPasswordActivity.class));
```
what this means is that ResetUserPasswordActivity's lifetime will be the whole app's duration. If the user dismisses `ResetUserPasswordActivity` it will still live in memory. Thus causing a memory leak.

You should be using the context of the current activity instead like

```
startActivity(new Intent(this, ResetUserPasswordActivity.class));
```

**Comment by ResurreccionErick** [comment]
Done, Thank you so much sir!
