### ISSUE TITLE
Good first issue: Code cleanup

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#5]
#### Issue
Commented imports and code blocks

#### Explanation
We should always strive for code to be maintainable and readable. 

#### To-do
Remove all commented code.

**Comment by FinnPixel** [comment]
Hey, I worked on issue #5 and tried to commit my changes. This did not work though, as I don't have the permission. What am I supposed to do?

**Comment by TenTraicion** [comment]
can i work in it?

**Comment by TenTraicion** [comment]
I have removed the commented out codes from the repo files in the PR #7 ,
Kindly check

**Comment by ResurreccionErick** [comment]
Clean/delete commented imports and some not necessary code blocks on my app.
