### ISSUE TITLE
Code refactor static variables in AlphabetActivity.java

### ISSUE THREAD

**Issue by lawgimenez** [ResurreccionErick/KG-CAI#6]
#### Issue
Static MediaPlayer variables leaks memories

#### Explanation
 `static MediaPlayer` variables are issues since `static` variables are not eligible for garbage collection and will live longer than the app. Plus each raw file allocates huge memories.

#### To-do
Migrate variables from `static` to good old Java POJO. And use background thread.

**Comment by ResurreccionErick** [comment]
Removed those activities with static as I upload my local files in firebase and fetch it on my application.
